// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hieypblvsqqpkdcwmnpc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhpZXlwYmx2c3FxcGtkY3dtbnBjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5MjM0MTQsImV4cCI6MjA2NjQ5OTQxNH0.5ZP4rH7KJaSNse5vF30a_lNJsbedJcj7M3Bn94ANJZk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);